repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        files: itsm-api/.*\.py$
      - id: ruff-format
        files: itsm-api/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: itsm-web/.*\.(ts|tsx|json|css|md)$
        additional_dependencies:
          - prettier@3.1.0
