apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "60s"
      queryTimeout: "60s"
      httpMethod: POST
